### REGISTER - New User
POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
  "firstName": "Gautam",
  "lastName": "Jaisur",
  "email": "gautam@example.com",
  "password": "gautam@##",
  "passwordConfirm": "gautam@##"
}

### LOGIN - Get Token
POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}
###

### Display all users


GET http://localhost:5000/api/v1/users/displayall



@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTg4OGQ3ZTZjMzdkOTgyNGE0MjNiMiIsImlhdCI6MTc0Njg1NDc4NSwiZXhwIjoxNzQ5NDNzg1fQ.lA6ydWDwNnQk933RVLdcfs7unV_0cufjc6D0PGaKVY4



### delete user by id 

DELETE http://localhost:5000/api/v1/users/681889b865306b79f8438db5
Authorization: Bearer {{token}}

###

PATCH  http://localhost:5000/api/v1/users/681ee989bbd8ab3cb44982eb
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstname" :"Gautam",
  "lastname":"J"
}






### CRUD OPERATION For  tour with admin 



### Create Tour with Local Image Path
POST http://localhost:5000/api/v1/tours
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mount Abu",
  "duration": 10,
  "maxGroupSize": 5,
  "difficulty": "difficult",
  "price": 2000,
  "summary": "Epic Everest adventure",
  "country": "Rajasthan",
  "startLocation": {
    "type": "Point",
    "coordinates": [86.9250, 27.9881],
    "address": "Rajasthan Airport",
    "description": "Starting point"
  },
  "imagePath": "uploads/test-image.jpeg"
}


### GET ALL TOURS

GET http://localhost:5000/api/v1/tours/
Authorization: :Bearer {{token}}


### 4. Update Tour
PATCH http://localhost:5000/api/v1/tours/681ee53a2594061097628f06
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 9000,
  "difficulty": "medium"
}



### DELETE TOUR BY ID

DELETE  http://localhost:5000/api/v1/tours/681ee53a2594061097628f06
Authorization: Bearer {{token}}





### booking CRUD OPERATION


