// export { default as Home } from './Home/Home'
export { default as Home } from './Home.jsx'
export { default as TourDetails } from './TourDetail.jsx'
export { default as Login } from './Login.jsx'
export { default as Register } from './Register.jsx'
export { default as Dashboard } from './Dashboard.jsx'
export { default as Profile } from './Profile.jsx'
export { default as Admin } from './Admin.jsx'
export { default as ForgotPassword } from './ForgetPassword.jsx'
export { default as ResetPassword } from './ResetPassword.jsx'
export { default as NotFound } from './NotFound.jsx'